spring:
  config:
    activate:
      on-profile: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    mongodb:
      uri: uri
  elasticsearch:
    uris: URI
oci:
  objectstorage:
    region: region
    namespace: namespace
    bucket: bucket

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    hp.home_protector.domain.community.security.JwtAuthFilter: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  secret: SECRET

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
